spring:
    application:
        name: ojh
    profiles:
        active: local  # 기본적으로 로컬 환경을 사용하도록 설정
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
---
auth:
    password: ${AUTH_PASSWORD}
    jwt-secret: ${AUTH_JWT_SECRET}
    token-expiration: 1800
---
springdoc:
    swagger-ui:
        path: /docs         # Swagger UI 접근 경로 변경
        display-request-duration: true
        syntax-highlight:
            theme: monokai
    api-docs:
        path: /docs-json
